import { getData } from "csv";
import { functions, splitBy } from "methods";
import { IModel, IReportData } from "types";

function reporting(
	csvRawData: string,
	modelToGenerate: string,
	date: string | undefined,
	models: {
		[key: string]: IModel;
	},
	separator = ","
): IReportData {
	const json = getData(csvRawData, separator);
	const model = models[modelToGenerate];

	if (!model || !splitBy[model.dataSource] || !functions[model.output])
		throw new Error(
			`The specified model : "${modelToGenerate}" does not exist or the split function "${model.dataSource}" does not exist. Model names are available in the Documentation.`
		);

	// Extract the keys generated by the split function, similar to processing.ts
	const labels = Object.keys(
		splitBy[model.dataSource].exec(json, model.dataSourceKey)
	).map((label) => (label && label !== "" ? label : "_NO_LABEL_"));

	const output: IReportData = functions[model.output].exec({
		categoriesToSelect: model.categories,
		input: splitBy[model.dataSource].exec(json, model.dataSourceKey),
		labels,
		categories: model.categories, // Add categories
		colors: [], // Add empty colors array for report functions
		date,
		values: model.values ? model.values.split(",") : [],
	}) as IReportData;

	return output;
}
export default reporting;
